title: Stijn Korver — F1 Data Engineer
email: stijn@korver.ai
description: Portfolio of F1 data engineering projects. Targeting Data Analytics Engineer at Audi Revolut F1 Team.
baseurl: ""
url: "https://korver.ai"

# Collections
collections:
  projects_en:
    output: true
    permalink: /projects/:name/

# Build Settings
remote_theme: null
plugins:
  - jekyll-feed

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
      lang: en
  - scope:
      path: ""
      type: projects_en
    values:
      lang: en
      layout: project

# Exclude from Processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
